use_frameworks!

platform :ios, '10.0'

target 'TCCycleScrollView_Example' do
  pod 'TCCycleScrollView', :path => '../'

  target 'TCCycleScrollView_Tests' do
    inherit! :search_paths

    
  end
end
